# docker/docker-compose.yml
version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: covid19_zookeeper
    ports:
      - "2181:2181"
    networks:
      - covid19_net

  kafka:
    image: wurstmeister/kafka:latest
    container_name: covid19_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "covid_data:1:1"
    networks:
      - covid19_net
    depends_on:
      - zookeeper

  postgres:
    image: postgres:13
    container_name: superset_postgres
    restart: always
    environment:
      POSTGRES_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - covid19_net

  redis:
    image: redis:6
    container_name: superset_redis
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - covid19_net

  spark:
    build:
      context: ..
      dockerfile: docker/spark/Dockerfile
    container_name: covid19_spark
    environment:
      - SPARK_MODE=master
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "4040:4040"
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ../src:/opt/spark/apps/src
    networks:
      - covid19_net
    depends_on:
      - kafka
      - postgres

  superset:
    build:
      context: ./superset
      dockerfile: Dockerfile
    container_name: covid19_superset
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      - FLASK_APP=superset.app:create_app()
      - SUPERSET_CONFIG_PATH=/app/pythonpath/superset_config.py
      - SUPERSET_SECRET_KEY=your_secret_key_here
      - SUPERSET_LOAD_EXAMPLES=yes
      - SUPERSET_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_DB=superset
      - DATABASE_HOST=postgres
      - DATABASE_PASSWORD=superset
      - DATABASE_USER=superset
      - DATABASE_PORT=5432
    ports:
      - "8088:8088"
    networks:
      - covid19_net

volumes:
  postgres_data:
  kafka_data:
  redis_data:

networks:
  covid19_net:
    name: covid19_net
    driver: bridge